##
## Main configuration file for the Perplex documentation
##

# The domain of the site
baseURL: 'https://perplex.desider.at'
title: Perplex
DefaultLanguageCode: en-us
DefaultContentLanguage: en
metaDataFormat: yaml
pluralizeListTitles: false
enableEmoji: true
enableGitInfo: true

timeout: 300000 # Milliseconds
refLinksErrorLevel: WARNING

taxonomies:
  tag: tags
  category: categories
  series: series

ignoreFiles:
  - doc/draft/.*
ignoreErrors:
  - error-missing-instagram-accesstoken
  - error-remote-getjson
