##
## Main configuration file for the Perplex documentation
##

# The domain of the site
baseURL: http://example.com
title: Perplex
DefaultLanguageCode: en-us
DefaultContentLanguage: en
metaDataFormat: yaml
pluralizeListTitles: false
enableEmoji: true
enableGitInfo: true

timeout: 500000 # Milliseconds
refLinksErrorLevel: WARNING

taxonomies:
  tag: tags
  category: categories
  series: series

ignoreErrors:
  - error-missing-instagram-accesstoken
  - error-remote-getjson
