##
## Main configuration file for the Perplex documentation
##

# The domain of the site
baseURL: http://perplex.desider.at
DefaultLanguageCode: en-us
DefaultContentLanguage: en
metaDataFormat: yaml
pluralizeListTitles: false
enableEmoji: true
enableGitInfo: true
disableHugoGeneratorInject: false

languages:
  en:
    languageCode: en-US
    languageName: English
    title: Perplex Documentation
    weight: 1
  de:
    languageCode: de-DE
    languageName: Deutsch
    title: Perplex Dokumentation
    weight: 2

module:
  mounts:
    # EN content
    - source: 'content/en'
      target: 'content'
      lang: 'en'
    # DE content
    - source: 'content/de'
      target: 'content'
      lang: 'de'

# Fill in the missing translations
    # This fills in the gaps in DE content with EN content
    - source: 'content/en'
      target: 'content'
      lang: 'de'

timeout: "600s"

outputs:
  home: [HTML, RSS]
  section: [HTML]

taxonomies:
  tag: tags
  category: categories
  series: series
  author: authors

refLinksErrorLevel: WARNING

ignoreErrors:
  - error-missing-instagram-accesstoken
  - error-remote-getjson

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: -1
  getcsv:
    dir: :cacheDir/:project
    maxAge: -1
  getjson:
    dir: :cacheDir/:project
    maxAge: -1
  getresource:
    dir: :resourceDir/:project
    maxAge: -1
  images:
    dir: :resourceDir/_gen
    maxAge: -1
  modules:
    dir: :cacheDir/modules
    maxAge: -1

build:
  buildStats:
    enable: true