#
# Imaging section
#

# Options for bitmap files

quality       : 80
anchor        : smart
hint          : photo
resampleFilter: mitchellnetravali

exif:
  includeFields: ""
  excludeFields: ""
  disableDate: false
  disableLatLong: false
