#
# Configuration section for Markdown rendering
#

# Goldmark is Commonmark-compliant
defaultMarkdownHandler: goldmark
goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    autoHeadingID: true
    autoHeadingIDType: github
    wrapStandAloneImageWithinParagraph: false
    attribute:
      block: true
      title: true
  renderer:
    hardWraps: true
    unsafe: false
    xhtml: false
highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  lineAnchors: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  noClasses: true
  style: github
  tabWidth: 4
