#
# Configuration section for Markdown rendering
#

# Goldmark is Commonmark-compliant
goldmark:
  extensions:
    SuperSub: true
  parser:
    wrapStandAloneImageWithinParagraph: false
    attribute:
      block: true
  renderer:
    hardWraps: true

highlight:
  anchorLineNos: true
  lineNumbersInTable: true
  noClasses: false
