#
# Configuration section for Markdown rendering
#

# Goldmark is Commonmark-compliant
goldmark:
  parser:
    wrapStandAloneImageWithinParagraph: false
    attribute:
      block: true
  renderer:
    hardWraps: true
  extensions:
    extras:
      insert:
        enable: true
      mark:
        enable: true
      subscript:
        enable: true
      superscript:
        enable: true

highlight:
  anchorLineNos: true
  lineNumbersInTable: true
  noClasses: false
