#
# Theme-specific parameters
#

# Site-wide default image. It gets overridden by
# a page- or section-specific front-matter parameter.
featImg: img/logo_Perplex_theme_for_Hugo_colored.svg
image:
  # Site wide favicon for browser and OS display
  favicon:
    svg: icon/favicon.svg
    png: icon/favicon.png
