#
# Theme-specific parameters
#

# logo: logo/Perplex.svg

# Site-wide fallback for the featured image.
featured: logo/Perplex.svg

# Site wide favicon for browser and OS display
favicon:
  svg: icon/favicon.svg
  png: icon/favicon.png

sourceURL: https://github.com/bowman2001/perplexdoc
sourceEditTree: edit/main/content
