#
# Configuration section for the listing of related pages
#

includeNewer: true
threshold: 80
toLower: false

indices:
  - name: categories
    weight: 35
  - name: tags
    weight: 15
  - name: series
    weight: 50
