#
# Configuration section for the listing of related pages
#

includeNewer: true
threshold: 30
toLower: false

indices:
  - name: categories
    weight: 30
  - name: tags
    weight: 40
  - name: series
    weight: 30
