#
# Hugo security settings
#

enableInlineShortcodes: false
exec:
  allow:
    - ^go$ # Needed for modules
    - ^npx$ # Needed for postcss
    - ^postcss$ # Post-process the CSS stylesheet
  osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
funcs:
  getenv:
    - ^HUGO_
http:
  methods:
    - (?i)GET|POST
  urls:
    - .*
