[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.94.2"
HUGO_ENABLEGITINFO = "true"

[context.feature]
command = "hugo --gc --minify --environment development"
